ALTER TYPE public.categoria_documento ADD VALUE IF NOT EXISTS 'DRENAGEM';
ALTER TYPE public.categoria_documento ADD VALUE IF NOT EXISTS 'CADASTRO_TOPOGRAFIA';
ALTER TYPE public.categoria_documento ADD VALUE IF NOT EXISTS 'URBANIZACAO_SINALIZACAO';